### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by abhi5794** [AlexErrant/Pentive#7]
Hey, when I try to log in, it asks for an alpha key and the GitHub signin does not work

**Comment by abhi5794** [comment]
Just went through the code, can I please join the alpha testing phase?

**Comment by abhi5794** [comment]
This does not support Kindle browsers so I'll not be using it

**Comment by AlexErrant** [comment]
Can you elaborate on what doesn't work on the Kindle browser? I'm [targeting ES2022](https://github.com/AlexErrant/Pentive/blob/2e826a75a3b6b726a8a97b395699a212dd0693ea/app/tsconfig.json#L5) with the vague idea of bumping it as [Baseline: Widely available](https://developer.mozilla.org/en-US/docs/Glossary/Baseline/Compatibility#baseline_badges) moves along. It could be that the Kindle browser doesn't support WASM, which I have a hard dependency on since I'm using SQLite-in-the-browser. Trying to figure out what the Kindle browser supports via Google isn't getting me good answers.

Also, FWIW Pentive is still very much a WIP and isn't reasonably usable by anyone who isn't me. I'm still making database changes and honestly, I'm on an old version of SQLite where the FTS5 extension occasionally corrupts the DB so... that isn't great. Easily fixible with an upgrade but I'm working on other architecturally significant features. You're more than welcome to play with https://app.pentive.com - the only reason to login is to upload/download cards (which needs some design work, I'm not yet satisfied with the UX of, say, uploading 100 cards, or downloading a select subset of those 100 cards - so not really looking for people to play with that yet >_>)
